name: rimrep
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10.9
  - xarray
  - ipython
  - ipykernel
  - netcdf4
  - bottleneck
  - dask
  - scipy
  - h5netcdf
  - zarr
  - cartopy=0.21.1
  - matplotlib
  - seaborn
  - geopandas
  - dask-geopandas
  - s3fs
  - owslib
  - pystac-client
  - pyarrow


